---

- name: Create Backend App Directory
  become: true
  file:
    path: ./backend-app
    state: directory


- name: "Move backend files to App Directory"
  become: true
  copy:
      src: /root/project/artifact.tar.gz
      dest: ./backend-app
      owner: ubuntu
      mode: 0777

- name: "Unzip backend files"
  become: true
  shell: |
    cd ./backend-app
    tar xvzf artifact.tar.gz .
    rm -rf ./artifact.tar.gz

- name: Install dependencies and Start App with PM2
  become: true
  shell: |
    cd ./backend-app
    npm install
    pm2 stop default
    pm2 start --name "udapeople-backend" -f ./dist/main.js
 
 
  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    NODE_ENV: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"