---

- name: Create Backend App Directory
  become: true
  file:
    path: ~/backend-app
    state: directory


- name: "Move backend files to App Directory"
  become: true
  copy:
      src: /root/project/artifact.tar.gz
      dest: ~/backend-app
      owner: ubuntu
      mode: 0777

- name: "Unzip backend files"
  become: true
  shell: |
    cd ~/backend-app
    tar xvzf artifact.tar.gz .
    rm -rf ./artifact.tar.gz

- name: Install dependencies and Start App with PM2
  become: true
  shell: |
    cd ~/backend-app
    npm i
    pm2 stop default
    pm2 start npm --name=backend-app --start