---

- name: Create Backend App Directory
  file:
    path: ~/backend-app
    state: directory

- name: Extract backend files to backend app directory
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: Install dependencies and Start App with PM2
  become: true
  shell: |
    cd ~/backend-app
    npm i
    pm2 stop default
    pm2 start npm --name=backend-app --start